# Generated by Django 3.2.13 on 2022-05-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senti', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Link',
        ),
    ]
