# Generated by Django 3.2.13 on 2022-05-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senti', '0002_rename_question_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='youtube_link',
            new_name='link',
        ),
    ]
